/**
 * EVOLUTION TREES (Collins, Sep 28 2026 — after Tower Dominion's building
 * upgrades): every limb has THREE stages, and at each stage you choose ONE of
 * two options. A path reads as letters: a Spitter "AAB".
 *
 * Price: stages 1 and 2 are all SCIENCE; stage 3 is science plus ONE royal
 * point. Science is otherwise spent only on combo engines.
 *
 * Shape of a tree: stage 1 is a SHAPE trade (fast vs heavy, wide vs far),
 * stage 2 grows a VERB, stage 3 (the royal one) TRANSFORMS the limb. Every
 * option changes what the limb does — never a flat "+5%". Verbs an evolution
 * grows count as the limb's own pips (amplifiers multiply them, choirs and
 * wards broadcast them), but they are not banked when the limb is eaten.
 */
import type { TowerFamily, UpgradeOption, UpgradeTree } from '../src/sim/types';

const o = (name: string, text: string, fx: Omit<UpgradeOption, 'name' | 'text'> = {}): UpgradeOption => ({ name, text, ...fx });

export const UPGRADE_COST = [
  { science: 10 },
  { science: 20 },
  { science: 30, royal: 1 },
] as const;

export const UPGRADES: Record<TowerFamily, UpgradeTree> = {
  spitter: [
    [o('Rapid Glands', 'fires 50% faster, hits 20% softer', { tempo: 1.5, potency: 0.8 }),
      o('Heavy Gobs', 'hits 70% harder, fires 25% slower', { potency: 1.7, tempo: 0.75 })],
    [o('Acid Spit', 'hits shred armor (+2 mister)', { pips: ['mister', 'mister'] }),
      o('Sticky Spit', 'hits slow (+2 snare)', { pips: ['tangler', 'tangler'] })],
    [o('Hydra Throat', 'three gobs per shot (+2 projectiles)', { pips: ['twin', 'twin'] }),
      o('Long Throat', 'double range, sees the cloaked, snipes supports', { reach: 2, pips: ['ocular'] })],
  ],
  burster: [
    [o('Wide Burst', '+25px blast, 15% softer', { add: { aoe: 25 }, potency: 0.85 }),
      o('Dense Burst', '60% harder, 12px tighter blast', { potency: 1.6, add: { aoe: -12 } })],
    [o('Shrapnel', 'kills leave caltrops, +hp (+2 spine)', { pips: ['spine', 'spine'] }),
      o('Napalm Polyps', 'blasts set bodies burning (+2 ember)', { pips: ['ember', 'ember'] })],
    [o('Cluster Polyps', 'each burst also strikes 2 more targets', { pips: ['quill', 'quill'] }),
      o('Skyburst', 'blasts reach the AIR and drag fliers down', { set: { hitsAir: true }, pips: ['net'] })],
  ],
  lasher: [
    [o('Long Whips', '40% more reach', { reach: 1.4 }),
      o('Barbed Whips', '50% harder lashes', { potency: 1.5 })],
    [o('Rending', 'lashes shred armor (+2 mister)', { pips: ['mister', 'mister'] }),
      o('Thrashing', 'lashes arc to 2 more bodies (+2 frond)', { pips: ['frond', 'frond'] })],
    [o('Hydra Lashes', 'every lash also strikes 2 more targets', { pips: ['quill', 'quill'] }),
      o('Gorger', 'digests the weak it touches, far richer meat', { pips: ['swamp', 'swamp', 'maw', 'maw', 'maw'] })],
  ],
  maw: [
    [o('Bigger Gullet', 'swallows bodies 60% bigger', { mult: { eatThreshold: 1.6 } }),
      o('Faster Jaws', 'bites 50% faster', { tempo: 1.5 })],
    [o('Rich Digestion', '+60% meat from its kills', { pips: ['maw', 'maw'] }),
      o('Acid Stomach', 'bites poison (+2 blight)', { pips: ['blighter', 'blighter'] })],
    [o('Swallow Whole', 'swallows bodies 2.5x bigger — elites go down whole', { mult: { eatThreshold: 2.5 } }),
      o('Regurgitate', 'spits chunks: splash and knockback', { pips: ['burster', 'burster', 'lobber', 'lobber'] })],
  ],
  spine: [
    [o('Thick Hide', '60% more hp', { mult: { maxHp: 1.6 } }),
      o('Barbs', 'double thorns on whatever chews it', { potency: 2 })],
    [o('Caltrop Shedding', 'thorn kills leave caltrops (+2 spine)', { pips: ['spine', 'spine'] }),
      o('Toxic Barbs', 'thorns poison (+2 blight)', { pips: ['blighter', 'blighter'] })],
    [o('Bone Fortress', '2.5x hp and a permanent shield', { mult: { maxHp: 2.5 }, pips: ['ward', 'ward'] }),
      o('Living Wall', 'regrows fully every wave and grows past full', { pips: ['brood', 'brood', 'brood'] })],
  ],
  lure: [
    [o('Strong Musk', 'clouds 60% more toxic', { potency: 1.6 }),
      o('Quick Pulse', 'pulses 60% more often', { tempo: 1.6 })],
    [o('Wide Cloud', '+20px cloud', { add: { aoe: 20 } }),
      o('Tar Musk', 'clouds slow (+2 snare)', { pips: ['tangler', 'tangler'] })],
    [o("Queen's Scent", '+10 interest; its clouds breed more clouds', { add: { interest: 10 }, pips: ['lure', 'lure'] }),
      o('Firedamp', 'clouds ignite (+3 ember)', { pips: ['ember', 'ember', 'ember'] })],
  ],
  tangler: [
    [o('Thick Mucus', 'slow bites 20% deeper', { mult: { slowMult: 0.8 } }),
      o('Wide Bed', '+20px mucus', { add: { aoe: 20 } })],
    [o('Caustic Mucus', 'mucus poisons (+2 blight)', { pips: ['blighter', 'blighter'] }),
      o('Grasping', 'reaches the air and drags fliers down', { pips: ['net', 'net'] })],
    [o('Tar Pit', 'slow halved again and lasts 2s longer', { mult: { slowMult: 0.5 }, add: { slowDur: 2 } }),
      o('Digestive Mucus', 'digests the weak it coats (+3 swamp)', { pips: ['swamp', 'swamp', 'swamp'] })],
  ],
  blighter: [
    [o('Virulent', '+5 poison dps', { add: { poisonDps: 5 } }),
      o('Lingering', 'poison lasts 3s longer', { add: { poisonDur: 3 } })],
    [o('Airborne Spores', 'reaches the AIR, +10px cloud', { set: { hitsAir: true }, add: { aoe: 10 } }),
      o('Rot', 'spores shred armor (+2 mister)', { pips: ['mister', 'mister'] })],
    [o('Plague', 'poison hits arc to 2 more bodies', { pips: ['frond', 'frond'] }),
      o('Necrosis', 'digests the weak it rots (+3 swamp)', { pips: ['swamp', 'swamp', 'swamp'] })],
  ],
  impaler: [
    [o('Heavy Harpoon', '50% harder, 20% slower', { potency: 1.5, tempo: 0.8 }),
      o('Quick Reload', 'fires 50% faster', { tempo: 1.5 })],
    [o('Barbed Harpoon', 'skewered bodies slow (+2 snare)', { pips: ['tangler', 'tangler'] }),
      o('Serrated', 'skewered bodies shred (+2 mister)', { pips: ['mister', 'mister'] })],
    [o('Railspine', 'double range, 50% harder', { reach: 2, potency: 1.5 }),
      o('Harpoon Volley', 'three harpoons per shot', { pips: ['twin', 'twin'] })],
  ],
  choir: [
    [o('Loud Choir', 'tempo aura 50% stronger', { potency: 1.5 }),
      o('Wide Choir', 'aura 50% wider', { reach: 1.5 })],
    [o('Chorus of Thorns', 'everything it covers gains thorns + caltrops', { pips: ['spine', 'spine'] }),
      o('Chorus of Venom', 'everything it covers poisons', { pips: ['blighter', 'blighter'] })],
    [o('Cathedral', 'aura twice as strong and 50% wider', { potency: 2, reach: 1.5 }),
      o('Choir of Chains', 'every hit of every covered limb arcs to 3 more', { pips: ['frond', 'frond', 'frond'] })],
  ],
  sling: [
    [o('Long Arm', 'throws 50% farther', { reach: 1.5 }),
      o('Quick Arm', 'rearms 60% faster', { tempo: 1.6 })],
    [o('Big Clots', '+20px creep patch and splash', { add: { aoe: 20 } }),
      o('Seeding', 'the sling itself seeps creep (+2 sling)', { pips: ['sling', 'sling'] })],
    [o('Barrage', 'three clots per throw', { pips: ['twin', 'twin'] }),
      o('Bone Clots', 'clots land 3x harder with a blast', { potency: 3, pips: ['burster', 'burster'] })],
  ],
  brood: [
    [o('Big Brood', '+2 broodlings', { add: { extraBroodlings: 2 } }),
      o('Quick Brood', 'hatches 60% faster', { tempo: 1.6 })],
    [o('Armoured Brood', 'broodlings 80% tougher', { mult: { maxHp: 1.8 } }),
      o('Venom Brood', 'broodling bites poison', { pips: ['blighter', 'blighter'] })],
    [o('Swarm Queen', '+4 broodlings', { add: { extraBroodlings: 4 } }),
      o('War Brood', 'broodlings bite twice as hard and roam 50% farther', { potency: 2, reach: 1.5 })],
  ],
  swamp: [
    [o('Deep Bog', 'burns 60% harder', { potency: 1.6 }),
      o('Wide Bog', '+16px swamp', { add: { aoe: 16 } })],
    [o('Gastric Acid', 'shreds armor (+2 mister)', { pips: ['mister', 'mister'] }),
      o('Quicksand', 'bogs deeper (+2 snare)', { pips: ['tangler', 'tangler'] })],
    [o('Great Gut', 'digests anything under +40 more hp', { add: { execute: 40 } }),
      o('Tar Fire', 'the swamp sets waders burning (+3 ember)', { pips: ['ember', 'ember', 'ember'] })],
  ],
  frond: [
    [o('Long Arc', 'arcs to 2 more bodies', { add: { chains: 2 } }),
      o('Hot Arc', '50% harder strikes', { potency: 1.5 })],
    [o('Stun Arc', 'arcs slow (+2 snare)', { pips: ['tangler', 'tangler'] }),
      o('Searing Arc', 'arcs ignite (+2 ember)', { pips: ['ember', 'ember'] })],
    [o('Storm Frond', 'arcs to 5 more bodies and fires twice', { add: { chains: 5 }, pips: ['twin'] }),
      o('Grounding Rod', 'drags fliers down and ramps on a held target', { pips: ['net', 'net', 'prism', 'prism'] })],
  ],
  lobber: [
    [o('Big Glob', '+20px blast', { add: { aoe: 20 } }),
      o('Quick Glob', 'rearms 60% faster', { tempo: 1.6 })],
    [o('Sticky Bile', 'globs slow (+2 snare)', { pips: ['tangler', 'tangler'] }),
      o('Burning Bile', 'globs ignite (+2 ember)', { pips: ['ember', 'ember'] })],
    [o('Triple Glob', 'three globs per volley', { pips: ['twin', 'twin'] }),
      o('Acid Rain', 'twice as hard and shreds armor', { potency: 2, pips: ['mister', 'mister'] })],
  ],
  mister: [
    [o('Deep Shred', '+6 shred', { add: { shred: 6 } }),
      o('Long Cling', 'shred lasts 3s longer', { add: { shredDur: 3 } })],
    [o('Tracer Mist', 'marked bodies take extra from everyone vs supports', { pips: ['ocular', 'ocular'] }),
      o('Choking Mist', 'mist poisons (+2 blight)', { pips: ['blighter', 'blighter'] })],
    [o('Dissolving Mist', '+15 shred and +20px mist', { add: { shred: 15, aoe: 20 } }),
      o('Weeping Mist', 'mist leaves toxic clouds (+2 lure)', { pips: ['lure', 'lure'] })],
  ],
  ocular: [
    [o('Quick Focus', 'fires 50% faster', { tempo: 1.5 }),
      o('Heavy Stare', '50% harder', { potency: 1.5 })],
    [o('Execution Stare', 'digests what it leaves weak (+2 swamp)', { pips: ['swamp', 'swamp'] }),
      o('Marking Stare', 'its target is shredded for everyone (+2 mister)', { pips: ['mister', 'mister'] })],
    [o('Twin Stalk', 'three beams per shot', { pips: ['twin', 'twin'] }),
      o('Death Glare', '3x damage', { potency: 3 })],
  ],
  prism: [
    [o('Focus Lens', 'ramps twice as fast on a held target', { add: { streakRamp: 0.06 } }),
      o('Wide Lens', '30% more range', { reach: 1.3 })],
    [o('Scorch', 'the beam ignites (+2 ember)', { pips: ['ember', 'ember'] }),
      o('Refract', 'the beam arcs to 2 more (+2 frond)', { pips: ['frond', 'frond'] })],
    [o('Overcharge', 'twice as hard, 30% faster', { potency: 2, tempo: 1.3 }),
      o('Grid Prism', '50% more range and every beam strikes 2 more', { reach: 1.5, pips: ['quill', 'quill'] })],
  ],
  bombard: [
    [o('Bigger Shell', '+20px blast', { add: { aoe: 20 } }),
      o('Faster Shell', 'fires 50% faster', { tempo: 1.5 })],
    [o('Spore Shell', 'shells poison (+2 blight)', { pips: ['blighter', 'blighter'] }),
      o('Incendiary', 'shells ignite (+2 ember)', { pips: ['ember', 'ember'] })],
    [o('Double Barrage', 'three shells per salvo', { pips: ['twin', 'twin'] }),
      o('Earthshaker', 'twice as hard and hurls bodies back', { potency: 2, pips: ['lobber', 'lobber', 'lobber'] })],
  ],
  ward: [
    [o('Thick Membrane', 'shields 60% stronger', { potency: 1.6 }),
      o('Wide Membrane', 'covers 50% wider', { reach: 1.5 })],
    [o('Quick Mend', 'shields regrow twice as fast', { tempo: 2 }),
      o('Barbed Membrane', 'everything it covers gains thorns + caltrops', { pips: ['spine', 'spine'] })],
    [o('Aegis', 'shields 2.5x stronger', { potency: 2.5 }),
      o('Grasping Membrane', 'every covered limb\'s hits slow', { pips: ['tangler', 'tangler', 'tangler'] })],
  ],
  quill: [
    [o('Tight Choke', 'quills 40% harder', { potency: 1.4 }),
      o('Long Fan', '40% more range', { reach: 1.4 })],
    [o('Barbed Quills', 'quills slow (+2 snare)', { pips: ['tangler', 'tangler'] }),
      o('Venom Quills', 'quills poison (+2 blight)', { pips: ['blighter', 'blighter'] })],
    [o('Porcupine', 'three fans per shot', { pips: ['twin', 'twin'] }),
      o('Bone Needles', '50% harder and pierces armor', { potency: 1.5, pips: ['impaler', 'impaler', 'impaler'] })],
  ],
  skipper: [
    [o('Extra Skip', 'skips 2 more times', { add: { skips: 2 } }),
      o('Heavy Shell', '50% harder', { potency: 1.5 })],
    [o('Burning Wake', 'every landing ignites (+2 ember)', { pips: ['ember', 'ember'] }),
      o('Sticky Wake', 'every landing slows (+2 snare)', { pips: ['tangler', 'tangler'] })],
    [o('Endless Skip', 'skips 6 more times', { add: { skips: 6 } }),
      o('Twin Mortar', 'three shells per shot', { pips: ['twin', 'twin'] })],
  ],
  net: [
    [o('Heavy Net', 'holds fliers down 2s longer', { add: { grounding: 2 } }),
      o('Fast Net', 'casts 50% faster', { tempo: 1.5 })],
    [o('Barbed Net', 'nets 40% harder', { pips: ['lasher', 'lasher'] }),
      o('Ground Web', 'can now net GROUND bodies too', { set: { hitsGround: true } })],
    [o('Storm Net', 'nets arc to 3 more', { pips: ['frond', 'frond', 'frond'] }),
      o('Flak Burst', 'twice as hard, +30px burst', { potency: 2, add: { aoe: 30 } })],
  ],
  ember: [
    [o('Hot Oil', '+6 burn dps', { add: { burnDps: 6 } }),
      o('Long Flame', '40% more range', { reach: 1.4 })],
    [o('Sticky Oil', 'burning bodies slow (+2 snare)', { pips: ['tangler', 'tangler'] }),
      o('Toxic Smoke', 'flames leave toxic clouds (+2 lure)', { pips: ['lure', 'lure'] })],
    [o('Inferno', '+15 burn dps, burns 3s longer', { add: { burnDps: 15, burnDur: 3 } }),
      o('Wildfire', 'flames arc to 3 more bodies', { pips: ['frond', 'frond', 'frond'] })],
  ],
  lance: [
    [o('Long Runner', 'the strip reaches 50% farther', { reach: 1.5 }),
      o('Broad Runner', 'the strip is one cell wider each side', { add: { aoe: 12 } })],
    [o('Quick Runner', 'the strip grows twice as fast', { tempo: 2 }),
      o('Deep Runner', 'twice the hp — the strip it holds is safer', { mult: { maxHp: 2 } })],
    [o('Great Runner', 'the strip reaches twice as far', { reach: 2 }),
      o('Delta', 'two cells wider each side and 30% longer', { add: { aoe: 24 }, reach: 1.3 })],
  ],
  cage: [
    [o('Wide Jaws', 'catches royals 50% farther away', { reach: 1.5 }),
      o('Early Snap', 'catches a royal at 70% hp instead of 50%', { add: { captureAt: 0.2 } })],
    [o('Iron Bars', 'twice the hp', { mult: { maxHp: 2 } }),
      o('Twin Cage', 'catches TWO royals', { add: { captures: 1 } })],
    [o('Puppet Master', 'your puppets bite twice as hard', { potency: 2 }),
      o('Hive Mind', 'your puppets move and bite 50% faster', { tempo: 1.5 })],
  ],
  // ---- combo engines: evolutions bend the ENGINE's rule ----
  conduit: [
    [o('Wide Gather', 'draws from 50% farther around it', { mult: { gather: 1.5 } }),
      o('Long Lane', 'feeds a limb twice as far away', { reach: 2 })],
    [o('Deep Channel', 'passes 3 copies of each bonus (not 2)', { add: { engineCap: 1 } }),
      o('Blood Rush', 'also pumps +1 tempo into its target', { targetPips: ['spitter'] })],
    [o('Great Conduit', '5 copies per bonus and 50% wider gather', { add: { engineCap: 3 }, mult: { gather: 1.5 } }),
      o('Marrow Pump', 'everything it passes arrives DOUBLED', { add: { poolMult: 1 } })],
  ],
  amp: [
    [o('Long Reach', 'amplifies a limb twice as far away', { reach: 2 }),
      o('Tuned', 'x1.6 per layer instead of x1.5', { add: { ampFactor: 0.1 } })],
    [o('Overtone', 'x1.75 per layer', { add: { ampFactor: 0.25 } }),
      o('Round Up', 'rounds UP: a single bonus becomes two', { set: { ampRoundUp: true } })],
    [o('Second Voice', 'counts as two amplifiers', { add: { ampExtraLayers: 1 } }),
      o('Ascendant', 'x2 per layer', { add: { ampFactor: 0.5 } })],
  ],
  mosaic: [
    [o('Wide Gather', 'finds tiles 50% farther around it', { mult: { gather: 1.5 } }),
      o('Long Lane', 'feeds a limb twice as far away', { reach: 2 })],
    [o('Double Tiles', 'TWO of each distinct type', { add: { mosaicCopies: 1 } }),
      o('Self Tile', 'also gives its target one more of its OWN family', { set: { targetSelf: true } })],
    [o('Triple Tiles', 'THREE of each distinct type', { add: { mosaicCopies: 2 } }),
      o('Grand Mosaic', 'twice the gather, twice the lane, two of each', { mult: { gather: 2 }, reach: 2, add: { mosaicCopies: 1 } })],
  ],
  twin: [
    [o('Long Reach', 'twins a limb twice as far away', { reach: 2 }),
      o('Spray', 'its target\'s shots also splash (+1 burster)', { targetPips: ['burster'] })],
    [o('Triplet', 'x3 projectiles instead of x2', { add: { twinPower: 1 } }),
      o('Split Shot', 'its target also strikes 1 more target', { targetPips: ['quill'] })],
    [o('Quad', 'x4 projectiles', { add: { twinPower: 2 } }),
      o('Echo Volley', 'x3 projectiles that ramp on a held target', { add: { twinPower: 1 }, targetPips: ['prism', 'prism'] })],
  ],
  tap: [
    [o('Long Tap', 'taps a limb twice as far away', { reach: 2 }),
      o('Gentle Tap', 'its target keeps working at half speed', { set: { gentleTap: true } })],
    [o('Deep Tap', 'each milking banks TWO copies', { add: { tapCopies: 1 } }),
      o('Siphon', 'each milking also pays 15 war', { add: { tapWar: 15 } })],
    [o('Wellspring', 'each milking banks THREE copies', { add: { tapCopies: 2 } }),
      o('Gentle Well', 'target works at half speed AND two copies', { set: { gentleTap: true }, add: { tapCopies: 1 } })],
  ],
  mitosis: [
    [o('Fertile', 'buds TWO copies a wave', { add: { budCount: 1 } }),
      o('Wide Womb', 'buds into spaces two cells out', { add: { budRing: 1 } })],
    [o('Grafted Buds', 'buds carry their own family bonus', { add: { budPips: 1 } }),
      o('Hardy Buds', 'three buds a wave', { add: { budCount: 2 } })],
    [o('True Copy', 'buds carry ALL of the parent\'s bonuses', { add: { budPips: 999 } }),
      o('Swarm Womb', 'four buds a wave, two cells out', { add: { budCount: 3, budRing: 1 } })],
  ],
  capacitor: [
    [o('Fast Charge', 'banks shots twice as fast', { add: { capCharge: 1 } }),
      o('Overclock', 'spends the bank at 600% speed', { add: { capSpeed: 2 } })],
    [o('Trickle', 'keeps banking at 25% while firing', { add: { capTrickle: 0.25 } }),
      o('Static', 'its target\'s shots arc (+1 frond)', { targetPips: ['frond'] })],
    [o('Supercap', 'spends the bank at 1000% speed', { add: { capSpeed: 6 } }),
      o('Thunderbank', 'banks 3x as fast and shots arc to 2 more', { add: { capCharge: 2 }, targetPips: ['frond', 'frond'] })],
  ],
  boomerang: [
    [o('Far Call', 'reaches a limb 50% farther away', { reach: 1.5 }),
      o('Heavy Return', 'return legs hit 50% harder', { mult: { returnDmg: 1.5 } })],
    [o('Ricochet', 'one more trip back out', { add: { returnLegs: 1 } }),
      o('Sticky Return', 'returning shots slow (+2 snare)', { targetPips: ['tangler', 'tangler'] })],
    [o('Orbit', 'three more trips — shots ping-pong down the lane', { add: { returnLegs: 3 } }),
      o('Razor Return', 'return legs hit twice as hard and pierce armor', { mult: { returnDmg: 2 }, targetPips: ['impaler', 'impaler'] })],
  ],
  press: [
    [o('Long Press', 'presses a limb twice as far away', { reach: 2 }),
      o('Rich Press', 'pressed kills pay 50% more science', { add: { pressBonus: 0.5 } })],
    [o('Richer Press', 'pressed kills pay 100% more science', { add: { pressBonus: 1 } }),
      o('Hungry Press', 'its target\'s kills pay 60% more of everything', { targetPips: ['maw', 'maw'] })],
    [o('Golden Press', 'pressed kills pay 250% more science', { add: { pressBonus: 2.5 } }),
      o('Royal Press', 'every 12th pressed kill pays a ROYAL point', { add: { pressRoyalEvery: 12 } })],
  ],
  reliquary: [
    [o('Long Vigil', 'guards a limb twice as far away', { reach: 2 }),
      o('Double Relic', 'banks TWO copies when its limb dies', { add: { relicCopies: 1 } })],
    [o('Resurrection', 'its limb is reborn (plain) where it died, once per wave', { add: { rebirth: 1 } }),
      o('Triple Relic', 'banks THREE copies when its limb dies', { add: { relicCopies: 2 } })],
    [o('Phoenix', 'its limb is reborn WITH its bonuses and evolutions, once per wave', { add: { rebirth: 2 } }),
      o('Martyr\'s Hoard', 'banks FIVE copies when its limb dies', { add: { relicCopies: 4 } })],
  ],
};
