import { spawn, execSync } from 'node:child_process';
import { chromium } from '@playwright/test';
const root = 'C:/Users/Merry/dev/space-derelict/games/broodfall';
const env = { ...process.env, BROODFALL_NO_HMR: '1', RFAB_API_BASE: 'http://localhost:3011' }; delete env.RFAB_API_KEY;
const child = spawn('npx.cmd', ['vite', '--port', '5249', '--strictPort'], { cwd: root, stdio: 'pipe', shell: true, env });
await new Promise((r) => child.stdout.on('data', (d) => { if (String(d).includes('localhost')) r(); }));
const b = await chromium.launch(); const p = await b.newPage(); p.setDefaultNavigationTimeout(180000);
p.on('console', (m) => { if (!/vite/.test(m.text())) console.log('PAGE', m.text()); });
await p.goto('http://localhost:5249/?seed=3');
await p.evaluate(async () => {
  const m = await import('/src/meta/yokePlayer.ts'); const u = await import('/src/ui/yokeAccount.ts');
  const store = { v: null, load() { return this.v; }, save(t) { this.v = t; console.log('SAVED ' + t.slice(0, 4)); }, clear() { this.v = null; } };
  const link = new m.PlayerLink({ base: '/rfab-api', store });
  const orig = link.pollConnect.bind(link);
  link.pollConnect = async (d) => { try { const r = await orig(d); console.log('POLL ' + JSON.stringify(r)); return r; } catch (e) { console.log('POLLERR ' + e); throw e; } };
  window.__acct = new u.YokeAccountUi(link, { changed() { console.log('CHANGED connected=' + !!window.__acct?.state?.connected); }, resumed() { console.log('RESUMED'); } });
  await window.__acct.refresh();
  window.__acct.click('acct-link', document.body);
});
await p.waitForTimeout(3000);
const code = await p.evaluate(() => window.__acct.code?.userCode); console.log('CODE', code);
const res = await fetch('http://localhost:3011/api/broodfall/yoke/connect/approve', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE5ZTI1NzRmLTg3OTQtNGRiNy04NTU1LTI1NjU1NjhhZWI1YiIsInVzZXJJZCI6ImE5ZTI1NzRmLTg3OTQtNGRiNy04NTU1LTI1NjU1NjhhZWI1YiIsImRiSWQiOiJhOWUyNTc0Zi04Nzk0LTRkYjctODU1NS0yNTY1NTY4YWViNWIiLCJlbWFpbCI6ImJyb29kZmFsbC10ZXN0ZXIyQHJmYWIubG9jYWwiLCJpYXQiOjE3OTA3ODAzMzUsImV4cCI6MTc5MDc5MTEzNSwiYXVkIjoicmZhYi1mcm9udGVuZCIsImlzcyI6InJmYWItYmFja2VuZCJ9.7CMDXPL9p-EMYItX1PnGgbeZU-4KJHN5WGPZQiKd-ig' }, body: JSON.stringify({ code }) });
console.log('APPROVE', res.status, JSON.stringify(await res.json()));
await p.waitForTimeout(15000);
console.log('FINAL', await p.evaluate(() => JSON.stringify({ connected: window.__acct.state?.connected, html: window.__acct.html().slice(0, 200) })));
await b.close(); execSync('taskkill /PID ' + child.pid + ' /T /F');
