/**
 * The design of every ACTUAL enemy unit in the game, one entry per kind in
 * content/data.ts ENEMIES. Collins, Sep 29 2026: "I would focus on trying to spec actual
 * game units rather than in the abstract". This file is the single source: the written
 * spec (assets/unit-spec.md) and the concept prompts are both generated from it.
 *
 * tier: the first wave tier the kind appears in (content/data.ts WAVE_TABLE).
 * r: its radius on the map in px at a 26 px cell (src/render/render.ts ENEMY_SIZE).
 * look: what is DRAWN. states: every picture the sprite needs beyond walking.
 */
export const UNITS = [
  // ---- WAR CASTE (orange markings). Dress: Eastern Orthodox. ----
  { kind: 'responder', name: 'Responder', caste: 'war', tier: 0, r: 5, hp: 20, body: 'human-like',
    job: 'The first on the scene. Weak, brave, and the whole of the first wave.',
    look: 'a small upright parish watchman in a plain orange kaftan and a soft cap, carrying a lantern on a pole in one hand and a hand bell in another',
    basis: 'worker ant', states: ['chewing a limb', 'dying'] },
  { kind: 'skitterling', name: 'Skitterling', caste: 'war', tier: 1, r: 3.5, hp: 12, body: 'beast',
    job: 'Fast swarm chaff. Also what a splitter bursts into.',
    look: 'a tiny round hatchling on six quick legs, bare, with one dab of orange paint on its back; always drawn as a pack',
    basis: 'ant hatchling', states: ['dying'] },
  { kind: 'militia', name: 'Militia', caste: 'war', tier: 1, r: 6, hp: 45, body: 'human-like',
    job: 'The town levy. The bulk of the early waves.',
    look: 'an upright townsman in his own plain clothes with an orange sash across the chest, a pointed dome helmet far too big for him, and a spear with a small orange pennant',
    basis: 'worker ant', states: ['chewing a limb', 'dying', 'being promoted to soldier'] },
  { kind: 'soldier', name: 'Soldier', caste: 'war', tier: 2, r: 8, hp: 90, body: 'human-like',
    job: 'The regular army. The bulk of the middle waves.',
    look: 'an upright regular in a long orange kaftan with gold braid across the chest, a pointed dome helmet that fits, and a long-handled crescent axe',
    basis: 'soldier ant', states: ['chewing a limb', 'dying', 'being promoted to elite'] },
  { kind: 'splitter', name: 'Splitter', caste: 'war', tier: 2, r: 9, hp: 75, body: 'beast',
    job: 'Shot dead, it bursts into two skitterlings. Swallowed whole by a maw, it does not.',
    look: 'a stout porter on four legs with a wicker pannier strapped to its back over an orange blanket, two hatchlings peeking out of the pannier',
    basis: 'wolf spider carrying her young', states: ['dying: the pannier breaks and two skitterlings run out'] },
  { kind: 'flier', name: 'Flier', caste: 'war', tier: 3, r: 6, hp: 55, body: 'human-like',
    job: 'Flies straight over blocks and walls to the core.',
    look: 'a winged lancer: a wasp with an upright torso in an orange tabard and a small dome helmet, carrying a lance with a long orange pennant, drawn in the air with its shadow on the ground below',
    basis: 'wasp', states: ['netted: on the ground, tangled in web, wings folded', 'dying'] },
  { kind: 'elite', name: 'Elite', caste: 'war', tier: 3, r: 11, hp: 200, body: 'human-like',
    job: 'The guard. Hits hard, takes a lot of killing.',
    look: 'a big upright guardsman with stag-beetle horns coming through a gilded dome helmet, a coat of small gold-edged plates, an orange cloak and a great two-handed axe',
    basis: 'stag beetle', states: ['chewing a limb', 'dying'] },
  { kind: 'mortar', name: 'Mortar beetle', caste: 'war', tier: 4, r: 9, hp: 95, body: 'machine',
    job: 'Stops 85 px out and lobs shells at your limbs from standoff.',
    look: 'a squat beetle on six legs carrying a short fat bronze mortar shaped like an upturned bell on its back, an orange band around the mortar, one small insect crewman in a kaftan loading it',
    basis: 'dung beetle', states: ['firing: the mortar smokes, the crewman ducks', 'dying'] },
  { kind: 'sapper', name: 'Sapper', caste: 'war', tier: 4, r: 7, hp: 130, body: 'human-like',
    job: 'Climbs your blocks and eats limbs directly. Every limb shoots a climbing sapper first.',
    look: 'a steeplejack: a termite with big cutting jaws, a leather apron over an orange shirt, a tool belt, a coil of rope over one shoulder and a climbing hook in each upper hand',
    basis: 'termite soldier', states: ['climbing a wall, seen on the face of a block', 'chewing a limb', 'dying'] },
  { kind: 'carapace', name: 'Carapace lord', caste: 'war', tier: 5, r: 10, hp: 160, body: 'machine',
    job: 'Blocks the first six hits outright. Big blows strip the shell; rapid fire wastes itself on it.',
    look: 'an ironclad beetle whose shell is a gilded onion dome in six segments, with an orange band around its base; a small head with big eyes peers out from under the rim',
    basis: 'ironclad beetle', states: ['six pictures of the shell: six segments down to none, plain brown shell beneath', 'dying'] },
  { kind: 'phalanx', name: 'Phalanx', caste: 'war', tier: 5, r: 13, hp: 750, body: 'machine',
    job: 'The shield wall. No single hit does more than 12. Slow and enormous.',
    look: 'a huge flat pill bug carrying a wall of tall painted shield panels in gold, deep blue and orange, like a screen of icons, with one small insect driver in a kaftan peering over the top',
    basis: 'pill bug', states: ['chewing a limb', 'dying: the panels fall flat'] },
  { kind: 'cannon', name: 'Siege cannon', caste: 'war', tier: 4, r: 10, hp: 160, body: 'machine',
    job: 'Walks until something of yours is in reach, braces, and shells it until destroyed.',
    look: 'a bombardier beetle whose abdomen is an ornate cast-bronze cannon barrel with orange bands, with two small insect crew in kaftans walking beside it',
    basis: 'bombardier beetle', states: ['deployed: legs braced wide, barrel raised, one crewman covering his ears', 'firing', 'packing up', 'dying'] },
  { kind: 'drummer', name: 'Drummer', caste: 'war', tier: 3, r: 9, hp: 70, body: 'human-like',
    job: 'Everything near it marches faster. Kill it first.',
    look: 'an upright cicada bell-ringer carrying a wooden yoke of three bronze bells across its shoulders, striking them with two hammers, in an orange kaftan',
    basis: 'cicada', states: ['ringing: the rings of sound are drawn by code', 'dying'] },
  { kind: 'bomber', name: 'Bomber', caste: 'war', tier: 4, r: 6, hp: 60, body: 'human-like',
    job: 'Runs at walls and organs and blows itself up.',
    look: 'a small running censer-bearer swinging a smoking golden censer on three chains, which is the bomb and glows yellow from inside; goggles, an orange scarf',
    basis: 'exploding ant', states: ['detonating', 'dying without detonating'] },
  { kind: 'tunneler', name: 'Tunneler', caste: 'war', tier: 6, r: 8, hp: 110, body: 'beast',
    job: 'Burrows under your outer line where nothing can hit it, and comes up behind it.',
    look: 'a cave digger: a mole cricket with two great digging claws, a lamp strapped to its head and a monk\'s hood pushed back, orange cord at the waist',
    basis: 'mole cricket', states: ['burrowed: only a travelling mound of broken street', 'surfacing out of the mound', 'chewing a limb', 'dying'] },
  { kind: 'stalker', name: 'Stalker', caste: 'war', tier: 3, r: 8, hp: 85, body: 'human-like',
    job: 'Cloaked. Only limbs that can see it can shoot it.',
    look: 'a stick-thin figure in a long dark hooded habit with an orange cord at the waist, carrying a curved knife',
    basis: 'stick insect', states: ['cloaked: a shimmer outline drawn by code', 'revealed', 'chewing a limb', 'dying'] },
  { kind: 'shadewing', name: 'Shadewing', caste: 'war', tier: 4, r: 6, hp: 60, body: 'human-like',
    job: 'A cloaked flier. Needs a limb that reaches the air AND can see it.',
    look: 'a moth with dusk-grey wings and a dark veil over its head, an orange thread along the hem of the veil, drawn in the air with its shadow below',
    basis: 'moth', states: ['cloaked: a shimmer outline drawn by code', 'revealed', 'netted on the ground', 'dying'] },
  { kind: 'ghostsapper', name: 'Ghost sapper', caste: 'war', tier: 5, r: 7, hp: 120, body: 'human-like',
    job: 'A cloaked sapper: climbs your blocks and eats limbs unseen.',
    look: 'the steeplejack again, in a dark hooded habit over the leather apron, climbing hooks wrapped in cloth to keep them quiet',
    basis: 'termite soldier', states: ['cloaked', 'revealed', 'climbing a wall', 'chewing a limb', 'dying'] },
  { kind: 'tender', name: 'Tender', caste: 'war', tier: 5, r: 7, hp: 80, body: 'human-like',
    job: 'Heals the bodies around it in pulses. Kill it first.',
    look: 'a sister of mercy in a pale habit and white veil with an orange cord at the waist, carrying a satchel of bandages and a small flask of oil',
    basis: 'nurse bee', states: ['healing: the pulse is drawn by code', 'dying'] },
  // ---- SCIENCE CASTE (teal markings). They come for your limbs, never the core. ----
  { kind: 'researcher', name: 'Researcher', caste: 'science', tier: 'visits', r: 6, hp: 34, body: 'human-like',
    job: 'Walks around your guns to your least defended limb, sedates it and carries it off.',
    look: 'a tall thin upright scholar in a white lab coat with a teal scarf, an empty brass specimen cage on its back and a long syringe pole',
    basis: 'mantis', states: ['sedating a limb', 'carrying a limb in the cage', 'dying: the limb falls out and re-roots'] },
  { kind: 'thief', name: 'Specimen thief', caste: 'science', tier: 'visits', r: 6, hp: 45, body: 'human-like',
    job: 'Slips through the same gaps, steals 15 war meat and runs.',
    look: 'a small hunched quick figure in a dark coat with a teal scarf, clutching an empty sack',
    basis: 'silverfish', states: ['running away with a full sack', 'dying: the meat spills back'] },
  { kind: 'infiltrator', name: 'Infiltrator', caste: 'science', tier: 'visits', r: 6, hp: 40, body: 'human-like',
    job: 'A cloaked researcher: limb theft you cannot see coming.',
    look: 'the researcher in a long dark coat buttoned to the chin, only the teal lining showing at the collar, specimen cage under a cloth',
    basis: 'mantis', states: ['cloaked', 'revealed', 'sedating a limb', 'carrying a limb', 'dying'] },
  { kind: 'dartgun', name: 'Sedation battery', caste: 'science', tier: 'visits', r: 9, hp: 90, body: 'machine',
    job: 'Braces in reach of your weakest limb and stuns it with darts so researchers can walk in. Eight darts, then it goes home.',
    look: 'a pale beetle carrying a brass rack of eight glass dart tubes with teal fluid, teal markings on its shell, one insect operator in a lab coat walking beside it',
    basis: 'pale ground beetle', states: ['deployed: legs braced, rack tilted up', 'firing a dart', 'spent: tubes empty, walking home', 'dying'] },
  // ---- ROYAL CASTE (gold). Only with a royal event. ----
  { kind: 'royal', name: 'The royal', caste: 'royal', tier: 'royal event', r: 20, hp: 1100, body: 'human-like',
    job: 'The jackpot and the hardest fight. War bodies near her hit harder and take less.',
    look: 'the queen: three times the height of a soldier, an upright torso in a white and gold robe with a jewelled collar, a tall domed jewelled crown, and a huge swollen abdomen carried behind her like the train of a gown; regal and tired',
    basis: 'termite queen', states: ['chewing a limb', 'caught in the trap cage', 'grafted: marching for you, a red graft on her neck', 'dying'] },
  { kind: 'consort', name: 'Consort', caste: 'royal', tier: 'royal event', r: 13, hp: 420, body: 'human-like',
    job: 'Promotes the nearest war body one rank every five seconds.',
    look: 'an upright officer in a dark green dress uniform with gold epaulettes and a gold sash, half the height of the queen, holding a short gold baton',
    basis: 'drone ant', states: ['promoting: raises the baton', 'chewing a limb', 'dying'] },
  { kind: 'matron', name: 'Veil matron', caste: 'royal', tier: 'royal event', r: 13, hp: 380, body: 'human-like',
    job: 'Every war body near her is cloaked while she lives. She is visible: kill her first.',
    look: 'a tall still figure under a long grey veil edged in gold that reaches the ground, hands folded, only her amber eyes showing',
    basis: 'lacewing', states: ['veiling: the ring is drawn by code', 'dying: the veil drops'] },
];

/** The sheets the units are drawn on: a handful at a time holds one style across them. */
export const SHEETS = [
  { slug: 'units-1-first-waves', title: 'The first waves (tiers 0 to 2)', kinds: ['responder', 'skitterling', 'militia', 'soldier', 'splitter'] },
  { slug: 'units-2-army', title: 'The army (tier 3)', kinds: ['elite', 'flier', 'drummer', 'stalker'],
    extra: ['THE FLIER NETTED: the same winged lancer on the ground, tangled in white web, wings folded'] },
  { slug: 'units-3-siege', title: 'Siege and sappers (tier 4)', kinds: ['sapper', 'bomber', 'mortar', 'cannon', 'shadewing'],
    extra: ['THE SIEGE CANNON DEPLOYED: the same beetle with its legs braced wide and the barrel raised, one crewman covering his ears'] },
  { slug: 'units-4-last', title: 'Everything they have (tiers 5 and 6)', kinds: ['phalanx', 'carapace', 'tender', 'ghostsapper', 'tunneler'],
    extra: ['THE CARAPACE LORD STRIPPED: the same beetle with its gilded dome knocked off, plain brown shell showing',
      'THE TUNNELER BURROWED: only a mound of broken paving stones with a little lamp light showing through'] },
  { slug: 'units-5-science', title: 'The science caste', kinds: ['researcher', 'thief', 'infiltrator', 'dartgun'],
    extra: ['THE RESEARCHER CARRYING: the same scholar walking away with a small pink fleshy organ locked in the cage on its back',
      'THE SEDATION BATTERY DEPLOYED: the same beetle with its legs braced and the rack of dart tubes tilted up'] },
  { slug: 'units-6-royal', title: 'The royal caste', kinds: ['royal', 'consort', 'matron'] },
];

export const unit = (kind) => UNITS.find((u) => u.kind === kind);
