/**
 * Writes assets/unit-spec.md from tools/art/units.mjs, and checks the list against the
 * game: every kind in content/data.ts ENEMIES must have an entry, and nothing extra.
 * Free: it generates no pictures.
 *
 *   node tools/art/unit-spec.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './rfab.mjs';
import { SHEETS, UNITS } from './units.mjs';

const data = fs.readFileSync(path.join(ROOT, 'content', 'data.ts'), 'utf8');
const block = data.slice(data.indexOf('export const ENEMIES'), data.indexOf('export const WAVE_TABLE'));
const inGame = [...block.matchAll(/\{ kind: '([a-z]+)', caste: '([a-z]+)'/g)].map((m) => ({ kind: m[1], caste: m[2] }));
const missing = inGame.filter((g) => !UNITS.some((u) => u.kind === g.kind)).map((g) => g.kind);
const extra = UNITS.filter((u) => !inGame.some((g) => g.kind === u.kind)).map((u) => u.kind);
const wrongCaste = UNITS.filter((u) => inGame.some((g) => g.kind === u.kind && g.caste !== u.caste)).map((u) => u.kind);
if (missing.length || extra.length || wrongCaste.length) {
  console.error(`unit spec does not match the game. missing: ${missing.join(', ') || 'none'}; not in the game: ${extra.join(', ') || 'none'}; wrong caste: ${wrongCaste.join(', ') || 'none'}`);
  process.exit(1);
}

// Size on the map when art is authored at 96 px per cell (the game draws a 26 px cell today).
const px = (r) => Math.round((r * 2 * 96) / 26 / 4) * 4;
const CASTE = { war: 'War (orange)', science: 'Science (teal)', royal: 'Royal (gold)' };
const lines = [];
lines.push('# Broodfall unit spec — every enemy in the game');
lines.push('');
lines.push('GENERATED by `node tools/art/unit-spec.mjs` from `tools/art/units.mjs`. Edit that file, not this one.');
lines.push('The script fails if this list and `content/data.ts` ENEMIES ever disagree.');
lines.push('');
lines.push('Collins, Sep 29 2026: "I would focus on trying to spec actual game units rather than in the');
lines.push('abstract." And, on contrast with the organism: "both forces look too monstrous … I can see it');
lines.push('working for the architecture of insects and their dress style (at least the warrior caste):');
lines.push('think eastern orthodox."');
lines.push('');
lines.push('## Rules for every unit');
lines.push('');
lines.push('- **Charming, not frightening.** Round heads, big amber eyes, small mandibles, no bare claws or');
lines.push('  spikes. They are dressed little people. The monster on this board is you.');
lines.push('- **A little cartoonish,** like late-1990s strategy game units: chunky, big heads and tools,');
lines.push('  bold shapes, caste colour in large patches. Realistic versions are for films only.');
lines.push('- **Dress is Eastern Orthodox:** kaftans, gold braid, pointed dome helmets, bells, censers, veils.');
lines.push('- **The dome is their shape:** dome helmets, domed crowns, a domed shell, as on their roofs.');
lines.push('- **NO REAL RELIGIOUS SYMBOL, EVER.** No crosses, no stars, no crescents. Their one emblem is a');
lines.push('  plain gold hexagon (a honeycomb cell); domes end in a plain gold ball. This is a game about');
lines.push('  exterminating these people. The image model adds crosses by itself whenever it is asked for');
lines.push('  Orthodox dress, so every picture is checked for them before it is kept.');
lines.push('- **Caste colour is clothing,** never the body: war orange, science teal, royal gold.');
lines.push('- **Machines have crew.** A cannon or a shield wall always shows a small dressed insect.');
lines.push('- **Drawn by code, not in the sprite:** cloak shimmer, burning, slow, poison, health arcs,');
lines.push('  aura rings, the sedation line.');
lines.push('- Every unit walks in 8 directions: 5 drawn, 3 mirrored.');
lines.push('');
lines.push(`${UNITS.length} units: ${UNITS.filter((u) => u.caste === 'war').length} war, ${UNITS.filter((u) => u.caste === 'science').length} science, ${UNITS.filter((u) => u.caste === 'royal').length} royal.`);
lines.push('');
for (const s of SHEETS) {
  lines.push(`## ${s.title}`);
  lines.push('');
  lines.push(`Concept sheet: \`notes/concepts/2026-09-29/${s.slug}.png\``);
  lines.push('');
  for (const k of s.kinds) {
    const u = UNITS.find((x) => x.kind === k);
    lines.push(`### ${u.name} (\`${u.kind}\`)`);
    lines.push('');
    lines.push('| | |');
    lines.push('|---|---|');
    lines.push(`| Caste | ${CASTE[u.caste]} |`);
    lines.push(`| Appears | ${typeof u.tier === 'number' ? `wave tier ${u.tier}` : u.tier} |`);
    lines.push(`| What it does | ${u.job} |`);
    lines.push(`| Kind of body | ${u.body} |`);
    lines.push(`| Looks like | ${u.look[0].toUpperCase()}${u.look.slice(1)}. |`);
    lines.push(`| Borrowed from | ${u.basis} |`);
    lines.push(`| Size on the map | ${px(u.r)} px across at 96 px per cell (radius ${u.r} in the game today); ${u.hp} hp |`);
    lines.push(`| Pictures beyond walking | ${u.states.map((x) => x[0].toUpperCase() + x.slice(1)).join('. ')}. |`);
    lines.push('');
  }
}
fs.writeFileSync(path.join(ROOT, 'assets', 'unit-spec.md'), `${lines.join('\n')}\n`);
console.log(`unit spec matches the game: ${UNITS.length} units. Written to ${path.join(ROOT, 'assets', 'unit-spec.md')}`);
